run:
  timeout: 5m
linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - ineffassign
    - unused
    - goimports
issues:
  exclude-rules:
    - path: _test\.go
      linters: [errcheck]
